export type Lang = 'en' | 'pt'

type Dictionary = Record<string, string>

export const dict: Record<Lang, Dictionary> = {
  en: {
    'language.label': 'Language: English',
    'theme.day': 'DAY',
    'theme.night': 'NIGHT',
    'theme.toDay': 'Switch to day theme',
    'theme.toNight': 'Switch to night theme',
    'nav.projects': 'Projects',
    'nav.projectsDescription': 'Selected engineering work.',
    'nav.timeline': 'Timeline',
    'nav.timelineDescription': 'Experience and education.',
    'nav.linkedin': 'Linkedin',
    'nav.linkedinDescription': 'My Linkedin page.',
    'nav.github': 'GitHub',
    'nav.githubDescription': 'My GitHub page.',
    'nav.openMenu': 'Open menu',
    'footer.location': 'Maringá, PR, Brazil',
    'home.eyebrow': 'AI-AUGMENTED FULLSTACK ENGINEER',
    'home.profile': 'PROFILE',
    'home.name': 'Marcelo Luiz Baraldi',
    'home.location': 'Maringá, PR, Brazil',
    'home.role': 'Backend Developer · Fullstack Reach',
    'home.about': 'ABOUT',
    'home.bio': 'Backend developer with 5 years of experience and fullstack reach, focused on TypeScript, system architecture and microservices. I build scalable, high-availability applications for high-volume data — including critical tax and fiscal solutions — and continuously work to optimize development processes and shorten delivery cycles.',
    'home.aiTitle': 'AI & ORCHESTRATION',
    'home.coreFocus': 'CORE FOCUS',
    'home.aiText': 'Hands-on experience building AI-assisted development workflows on agentic systems. I design and operate the harness that coordinates agents, tools and context, and I extend it through plugins (MCP servers, custom commands and configured agents), skills (reusable, versioned playbooks the harness loads on demand) and deliberate context management for token efficiency. I orchestrate specialized sub-agents across research, implementation and review, and I tune how context is scoped, cached and reused so large tasks stay within budget while architecture, verification and delivery remain under explicit human direction.',
    'home.stack': 'STACK',
    'home.skills.languages': 'LANGUAGES',
    'home.skills.languagesItems': 'TypeScript · Go · Java',
    'home.skills.frontend': 'FRONTEND',
    'home.skills.frontendItems': 'React · Next.js · Tailwind CSS',
    'home.skills.backend': 'BACKEND',
    'home.skills.backendItems': 'Node.js · NestJS · FastAPI',
    'home.skills.apis': 'APIS',
    'home.skills.apisItems': 'REST · gRPC · GraphQL',
    'home.skills.cloud': 'CLOUD / DEVOPS',
    'home.skills.cloudItems': 'AWS · Docker · Kubernetes · ArgoCD · CI/CD',
    'home.skills.data': 'DATA',
    'home.skills.dataItems': 'PostgreSQL · MongoDB · Redis',
    'home.skills.more': 'Microservices Architecture · System Design · NX Monorepo · Observability · English B2/C1',
    'home.avatarAlt': 'Marcelo Luiz Baraldi',
    'home.artAlt': 'Pixel art developer at a workstation',
    'projects.eyebrow': 'PROJECTS',
    'projects.title': 'Selected Work',
    'projects.intro': 'Selected open-source and personal projects — from agentic tooling and fiscal validation APIs to quantitative trading and self-hosted infrastructure.',
    'projects.ai.label': 'PERSONAL · FEATURED',
    'projects.ai.title': 'AI & Agent Orchestration',
    'projects.ai.description': 'Designing multi-agent coding workflows on agentic systems. I build the harness that wires agents to tools and context, extend it with plugins (MCP servers, custom commands, agent presets) and skills (reusable workflows the harness invokes), and drive token efficiency through context scoping, session reuse and bounded delegation. Real development tasks are automated with explicit verification and human oversight.',
    'projects.ai.stack1': 'opencode',
    'projects.ai.stack2': 'codex',
    'projects.ai.stack3': 'Multi-agent workflows',
    'projects.ai.stack4': 'Automation',
    'projects.backend.label': 'PROFESSIONAL · TECNOSPEED',
    'projects.backend.title': 'Large-scale Backend',
    'projects.backend.description': 'Engineering critical fiscal microservices and APIs for high-availability, high-volume-data environments. The work spans gRPC and REST services, asynchronous processing and cloud infrastructure using AWS ECS, SQS and Lambda.',
    'projects.backend.stack1': 'TypeScript',
    'projects.backend.stack2': 'Microservices',
    'projects.backend.stack3': 'gRPC / REST',
    'projects.backend.stack4': 'AWS',
    'projects.quota.label': 'PERSONAL · TOOL',
    'projects.quota.title': 'Quota',
    'projects.quota.description': 'An interactive Go terminal dashboard that monitors the AI coding agents installed on your machine — Codex, OpenCode, Claude Code and DeepSeek. It auto-detects each agent CLI, reads rate limits and usage, and shows a live panel per agent so you can track consumption at a glance.',
    'projects.quota.stack1': 'Go',
    'projects.quota.stack2': 'Bubble Tea',
    'projects.quota.stack3': 'JSON-RPC',
    'projects.quota.stack4': 'OAuth',
    'projects.babel.label': 'PERSONAL · API',
    'projects.babel.title': 'Projeto Babel',
    'projects.babel.description': 'An API for the structural and fiscal validation of Brazilian electronic documents — NF-e, NFC-e and CT-e. It validates XML against the official XSD schemas, applies business and tax rules per document type, and returns structured rejections with correction guidance. Built in layered Clean Architecture and shipped as a container image.',
    'projects.babel.stack1': 'Bun',
    'projects.babel.stack2': 'Elysia',
    'projects.babel.stack3': 'TypeScript',
    'projects.babel.stack4': 'XML / XSD',
    'projects.algotrad.label': 'PERSONAL · RESEARCH',
    'projects.algotrad.title': 'Algo Trad',
    'projects.algotrad.description': 'A local, single-user application for quantitative research, backtesting and paper trading of BTCUSDT. It ingests public Binance and Bybit data, materializes indicators (CVD, basis, liquidity, heatmaps, multi-venue context) and exposes a full web UI for strategy analysis and simulation. Engineered with explicit context gates and reproducible backtests.',
    'projects.algotrad.stack1': 'Python',
    'projects.algotrad.stack2': 'Parquet',
    'projects.algotrad.stack3': 'WebSocket',
    'projects.algotrad.stack4': 'pytest',
    'projects.homelab.label': 'PERSONAL · INFRA',
    'projects.homelab.title': 'Homelab',
    'projects.homelab.description': 'A personal self-hosted infrastructure: container orchestration, networking, reverse proxy and observability for the services I run at home. It hosts long-running workloads such as the tiny-algo-trad daemon (24/7 paper trading) and codifies the setup as reproducible, version-controlled configuration.',
    'projects.homelab.stack1': 'Docker',
    'projects.homelab.stack2': 'Linux',
    'projects.homelab.stack3': 'systemd',
    'projects.homelab.stack4': 'CI/CD',
    'projects.technologies': 'technologies',
    'timeline.eyebrow': 'CAREER HISTORY',
    'timeline.title': 'Experience & Education',
    'timeline.intro': 'A path from cinema and teaching into software engineering, with a focus on backend systems, architecture and AI-assisted development.',
    'timeline.1.period': '04/2021 — PRESENT',
    'timeline.1.title': 'Software Developer · TecnoSpeed TI',
    'timeline.1.text': 'Based in Maringá, Marcelo develops critical tax and fiscal systems with a strong backend focus. His work spans TypeScript, microservices, gRPC and REST APIs, AWS services, high-availability applications and high-volume data. He also contributes to better development processes and more efficient delivery.',
    'timeline.2.period': '2026',
    'timeline.2.title': 'MBA in Software Engineering · USP Esalq',
    'timeline.2.text': 'Advanced study in software engineering, reinforcing his practical experience with architecture, system design and the delivery of robust, scalable products.',
    'timeline.3.period': '2022',
    'timeline.3.title': 'Systems Analysis & Development · PUC-PR',
    'timeline.3.text': 'Marcelo completed his technology degree after returning to formal study in software development. The program strengthened the technical foundation behind his transition into backend and fullstack engineering.',
    'timeline.4.period': '01/2016 — 01/2023',
    'timeline.4.title': 'Video Producer · Patagonia Filmes',
    'timeline.4.text': 'Alongside his transition into technology, Marcelo worked in audiovisual production, combining planning, technical execution and creative problem-solving across professional projects.',
    'timeline.5.period': '01/2018 — 12/2020',
    'timeline.5.title': 'Professor · Faculdade Eficaz',
    'timeline.5.text': 'He taught in the Audiovisual Production course, translating technical and creative subjects into clear learning experiences for students.',
    'timeline.6.period': '2011 — 2016',
    'timeline.6.title': 'Cinema & Audiovisual Practice',
    'timeline.6.text': 'Marcelo worked as a cinematographer, imaging director, videomaker and researcher. These roles developed his ability to coordinate complex work, communicate across disciplines and balance objective requirements with creative judgment.',
    'timeline.7.period': '2012',
    'timeline.7.title': 'Film, Cinema & Video Studies · UFSC',
    'timeline.7.text': 'He graduated from the Federal University of Santa Catarina. His cinema education broadened his perspective and continues to inform the way he approaches systems, people and product decisions.',
    'notFound.label': '404 / PAGE NOT FOUND',
    'notFound.title': 'The requested page is unavailable.',
    'notFound.text': 'The address may be incorrect, or the page may have moved.',
    'notFound.return': 'RETURN HOME',
  },
  pt: {
    'language.label': 'Idioma: Português',
    'theme.day': 'DIA',
    'theme.night': 'NOITE',
    'theme.toDay': 'Mudar para o tema claro',
    'theme.toNight': 'Mudar para o tema escuro',
    'nav.projects': 'Projetos',
    'nav.projectsDescription': 'Trabalhos selecionados de engenharia.',
    'nav.timeline': 'Trajetória',
    'nav.timelineDescription': 'Experiência e formação.',
    'nav.linkedin': 'Linkedin',
    'nav.linkedinDescription': 'Meu perfil no Linkedin.',
    'nav.github': 'GitHub',
    'nav.githubDescription': 'Meu perfil no GitHub.',
    'nav.openMenu': 'Abrir menu',
    'footer.location': 'Maringá, PR, Brasil',
    'home.eyebrow': 'ENGENHEIRO FULLSTACK POTENCIALIZADO POR IA',
    'home.profile': 'PERFIL',
    'home.name': 'Marcelo Luiz Baraldi',
    'home.location': 'Maringá, PR, Brasil',
    'home.role': 'Desenvolvedor Backend · Atuação Fullstack',
    'home.about': 'SOBRE',
    'home.bio': 'Desenvolvedor backend com 5 anos de experiência e atuação fullstack, focado em TypeScript, arquitetura de sistemas e microservices. Construo aplicações escaláveis e de alta disponibilidade para grandes volumes de dados — incluindo soluções fiscais críticas — e atuo continuamente para otimizar processos de desenvolvimento e reduzir ciclos de entrega.',
    'home.aiTitle': 'IA & ORQUESTRAÇÃO',
    'home.coreFocus': 'FOCO PRINCIPAL',
    'home.aiText': 'Experiência prática construindo fluxos de desenvolvimento assistidos por IA em sistemas agenticos. Projeto e opero o harness que coordena agentes, ferramentas e contexto, e o estendo por meio de plugins (servidores MCP, comandos customizados e agentes configurados), skills (playbooks reutilizáveis e versionados que o harness carrega sob demanda) e gestão deliberada de contexto para eficiência de tokens. Orquestro sub-agentes especializados em pesquisa, implementação e revisão, e ajusto como o contexto é delimitado, cacheado e reutilizado para que tarefas grandes fiquem dentro do orçamento, mantendo arquitetura, verificação e entrega sob direção humana explícita.',
    'home.stack': 'STACK',
    'home.skills.languages': 'LINGUAGENS',
    'home.skills.languagesItems': 'TypeScript · Go · Java',
    'home.skills.frontend': 'FRONTEND',
    'home.skills.frontendItems': 'React · Next.js · Tailwind CSS',
    'home.skills.backend': 'BACKEND',
    'home.skills.backendItems': 'Node.js · NestJS · FastAPI',
    'home.skills.apis': 'APIS',
    'home.skills.apisItems': 'REST · gRPC · GraphQL',
    'home.skills.cloud': 'CLOUD / DEVOPS',
    'home.skills.cloudItems': 'AWS · Docker · Kubernetes · ArgoCD · CI/CD',
    'home.skills.data': 'DADOS',
    'home.skills.dataItems': 'PostgreSQL · MongoDB · Redis',
    'home.skills.more': 'Arquitetura de Microservices · System Design · NX Monorepo · Observabilidade · Inglês B2/C1',
    'home.avatarAlt': 'Marcelo Luiz Baraldi',
    'home.artAlt': 'Arte em pixel de um desenvolvedor em sua estação de trabalho',
    'projects.eyebrow': 'PROJETOS',
    'projects.title': 'Trabalhos Selecionados',
    'projects.intro': 'Projetos de código aberto e pessoais selecionados — de ferramentas agenticas e APIs de validação fiscal a trading quantitativo e infraestrutura autohospedada.',
    'projects.ai.label': 'PESSOAL · DESTAQUE',
    'projects.ai.title': 'IA & Orquestração de Agentes',
    'projects.ai.description': 'Design de fluxos de codificação multi-agente em sistemas agenticos. Construo o harness que conecta agentes a ferramentas e contexto, estendo-o com plugins (servidores MCP, comandos customizados, presets de agentes) e skills (fluxos reutilizáveis que o harness invoca), e impulso a eficiência de tokens por meio de delimitação de contexto, reuso de sessão e delegação limitada. Tarefas reais de desenvolvimento são automatizadas com verificação explícita e supervisão humana.',
    'projects.ai.stack1': 'opencode',
    'projects.ai.stack2': 'codex',
    'projects.ai.stack3': 'Fluxos multi-agente',
    'projects.ai.stack4': 'Automação',
    'projects.backend.label': 'PROFISSIONAL · TECNOSPEED',
    'projects.backend.title': 'Backend em Grande Escala',
    'projects.backend.description': 'Engenharia de microservices e APIs fiscais críticos para ambientes de alta disponibilidade e grande volume de dados. O trabalho abrange serviços gRPC e REST, processamento assíncrono e infraestrutura em nuvem com AWS ECS, SQS e Lambda.',
    'projects.backend.stack1': 'TypeScript',
    'projects.backend.stack2': 'Microservices',
    'projects.backend.stack3': 'gRPC / REST',
    'projects.backend.stack4': 'AWS',
    'projects.quota.label': 'PESSOAL · FERRAMENTA',
    'projects.quota.title': 'Quota',
    'projects.quota.description': 'Um dashboard interativo em terminal, feito em Go, que monitora os agentes de IA de codificação instalados na máquina — Codex, OpenCode, Claude Code e DeepSeek. Detecta automaticamente o CLI de cada agente, lê limites de uso e exibe um painel ao vivo por agente para acompanhar o consumo de forma prática.',
    'projects.quota.stack1': 'Go',
    'projects.quota.stack2': 'Bubble Tea',
    'projects.quota.stack3': 'JSON-RPC',
    'projects.quota.stack4': 'OAuth',
    'projects.babel.label': 'PESSOAL · API',
    'projects.babel.title': 'Projeto Babel',
    'projects.babel.description': 'Uma API para validação estrutural e fiscal de documentos eletrônicos brasileiros — NF-e, NFC-e e CT-e. Valida o XML contra os schemas XSD oficiais, aplica regras de negócio e fiscais por tipo de documento e devolve rejeições estruturadas com orientação de correção. Organizada em Clean Architecture e publicada como imagem container.',
    'projects.babel.stack1': 'Bun',
    'projects.babel.stack2': 'Elysia',
    'projects.babel.stack3': 'TypeScript',
    'projects.babel.stack4': 'XML / XSD',
    'projects.algotrad.label': 'PESSOAL · PESQUISA',
    'projects.algotrad.title': 'Algo Trad',
    'projects.algotrad.description': 'Aplicativo local de usuário único para pesquisa quantitativa, backtest e paper trading de BTCUSDT. Coleta dados públicos da Binance e Bybit, materializa indicadores (CVD, basis, liquidez, heatmaps, contexto multi-venue) e expõe uma interface web completa para análise e simulação de estratégias. Construído com gates de contexto explícitos e backtests reproduzíveis.',
    'projects.algotrad.stack1': 'Python',
    'projects.algotrad.stack2': 'Parquet',
    'projects.algotrad.stack3': 'WebSocket',
    'projects.algotrad.stack4': 'pytest',
    'projects.homelab.label': 'PESSOAL · INFRA',
    'projects.homelab.title': 'Homelab',
    'projects.homelab.description': 'Infraestrutura pessoal autohospedada: orquestração de containers, rede, reverse proxy e observabilidade para os serviços que rodo em casa. Hospeda cargas de longa duração, como o daemon tiny-algo-trad (paper trading 24/7), e codifica o ambiente como configuração reproduzível e versionada.',
    'projects.homelab.stack1': 'Docker',
    'projects.homelab.stack2': 'Linux',
    'projects.homelab.stack3': 'systemd',
    'projects.homelab.stack4': 'CI/CD',
    'projects.technologies': 'tecnologias',
    'timeline.eyebrow': 'TRAJETÓRIA PROFISSIONAL',
    'timeline.title': 'Experiência & Formação',
    'timeline.intro': 'Uma trajetória do cinema e da docência à engenharia de software, com foco em sistemas backend, arquitetura e desenvolvimento assistido por IA.',
    'timeline.1.period': '04/2021 — PRESENTE',
    'timeline.1.title': 'Desenvolvedor de Software · TecnoSpeed TI',
    'timeline.1.text': 'Em Maringá, Marcelo desenvolve sistemas fiscais críticos com forte atuação em backend. Seu trabalho envolve TypeScript, microservices, APIs gRPC e REST, serviços AWS, aplicações de alta disponibilidade e grandes volumes de dados. Também contribui para aprimorar processos de desenvolvimento e tornar as entregas mais eficientes.',
    'timeline.2.period': '2026',
    'timeline.2.title': 'MBA em Engenharia de Software · USP Esalq',
    'timeline.2.text': 'Formação avançada em engenharia de software, reforçando sua experiência prática em arquitetura, system design e entrega de produtos robustos e escaláveis.',
    'timeline.3.period': '2022',
    'timeline.3.title': 'Análise e Desenvolvimento de Sistemas · PUC-PR',
    'timeline.3.text': 'Marcelo concluiu sua graduação em tecnologia após retornar aos estudos formais em desenvolvimento de software. O curso fortaleceu a base técnica por trás de sua transição para a engenharia backend e fullstack.',
    'timeline.4.period': '01/2016 — 01/2023',
    'timeline.4.title': 'Produtor de Vídeo · Patagonia Filmes',
    'timeline.4.text': 'Durante sua transição para a tecnologia, Marcelo trabalhou com produção audiovisual, combinando planejamento, execução técnica e resolução criativa de problemas em projetos profissionais.',
    'timeline.5.period': '01/2018 — 12/2020',
    'timeline.5.title': 'Professor · Faculdade Eficaz',
    'timeline.5.text': 'Lecionou no curso de Produção Audiovisual, transformando temas técnicos e criativos em experiências de aprendizagem claras para os alunos.',
    'timeline.6.period': '2011 — 2016',
    'timeline.6.title': 'Prática em Cinema & Audiovisual',
    'timeline.6.text': 'Marcelo atuou como diretor de fotografia, diretor de imagem, videomaker e pesquisador. Essas funções desenvolveram sua capacidade de coordenar trabalhos complexos, comunicar-se entre disciplinas e equilibrar requisitos objetivos com julgamento criativo.',
    'timeline.7.period': '2012',
    'timeline.7.title': 'Estudos em Filme, Cinema e Vídeo · UFSC',
    'timeline.7.text': 'Graduou-se pela Universidade Federal de Santa Catarina. Sua formação em cinema ampliou sua perspectiva e continua influenciando a forma como aborda sistemas, pessoas e decisões de produto.',
    'notFound.label': '404 / PÁGINA NÃO ENCONTRADA',
    'notFound.title': 'A página solicitada não está disponível.',
    'notFound.text': 'O endereço pode estar incorreto ou a página pode ter sido movida.',
    'notFound.return': 'VOLTAR AO INÍCIO',
  },
}
